modified README.md
NYAN-C4T/chat-space pull request #2
Opened 2017-01-07 11:27 UTC by NYAN-C4T

2017-01-07 11:57 UTC, caminogr requested changes

2017-01-07 11:57 UTC, kaminora commented on .idea/.generators
> +--><GeneratorsGroup><Generator name="assets" /><Generator name="channel" /><Generator name="coffee:assets" /><Generator name="controller" /><Generator name="generator" /><Generator name="helper" /><G
.idea/ディレクトリ以下のファイルはこのprojectには必要ないものですね！
gitignoreファイルを使ってgithugに上がらないようにしてみてください！！
gitignoreに関しては一度調べてみてください！！

2017-01-07 11:57 UTC, kaminora commented on README.md
> +( * = not null, _Italics_ are indexed)
一つのgroupには複数のuserがいる可能性があるので
group has_many usersの関係が成り立ちますよね？？
それを考慮してもう一度テーブル設計を考えてみてください！

2017-01-07 11:57 UTC, kaminora commented on README.md
> +( * = not null, _Italics_ are indexed)
ヒントですが、userモデルとgroupモデルの間には多対多の関係が成り立ちます！

2017-01-09 11:04 UTC, NYAN-C4T commented on .idea/.generators
> +--><GeneratorsGroup><Generator name="assets" /><Generator name="channel" /><Generator name="coffee:assets" /><Generator name="controller" /><Generator name="generator" /><Generator name="helper" /><G
.gitignoreを修正してみました。
ありがとうございます。

2017-01-09 11:13 UTC, NYAN-C4T commented on README.md
> +( * = not null, _Italics_ are indexed)
編集してみましたが、確証が持てません...
ありがとうございます。

2017-01-09 11:25 UTC, hotarak commented
細かいですが、#WHAT #WHYが大文字になっていないので、大文字にしましょう。

# WHATのように「#」の後に半角スペースを入れてみてください。

2017-01-09 11:25 UTC, hotarak commented on README.md
> +* has many **Users**
いいですね！こうすることで、ユーザーは複数のグループに所属でき、またグループは複数のユーザーを持つという多対多の関係性が成り立ちます。

しかし、このままではまだ未完全です。多対多の関係を扱うために、「どのユーザーがどのグループに所属しているか」を記録するための中間テーブルを作る必要があります！

2017-01-09 11:28 UTC, NYAN-C4T commented
@hotarak
修正しました。ご指摘ありがとうございます。

2017-01-09 11:59 UTC, FumiyaMori commented
UserとGroupは多対多の関係があるので中間テーブルも考えてみましょう

2017-01-09 12:00 UTC, FumiyaMori commented
.ideaディレクトリがまだgitで管理されてしまっているようですので修正しましょう

2017-01-17 07:46 UTC, NYAN-C4T commented
中間テーブルを検討してみました。
お手数ですが、レビューお願いします。

2017-01-17 08:07 UTC, KoichiOzaki commented on .gitignore
> +>>>>>>> master
この部分ですが、競合が発生した際に自動記述されたものですかね？
競合解決が終わっていれば消してもらって大丈夫です。

2017-01-17 08:07 UTC, KoichiOzaki commented on .gitignore
> +>>>>>>> master
この部分ですが、競合が発生した際に自動記述されたものですかね？
競合解決が終わっていれば消してもらって大丈夫です。

2017-01-17 08:12 UTC, KoichiOzaki commented on .gitignore
> +>>>>>>> master
この修正が終わったらマージして次に進んでもらって結構です！

2017-01-17 08:16 UTC, NYAN-C4T commented on .gitignore
> +>>>>>>> master
承知しました。
レビューありがとうございます！

2017-01-17 08:59 UTC, merged